### ISSUE TITLE
Error on: https://www.kamu.dev/blog/kamu-update-2021-03/a-brief-history-of-time-in-data-modelling-oltp-systems.md

### ISSUE THREAD

**Issue by JvD007** [kamu-data/open-data-fabric#4]
I got the following 404 message:

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: blog/kamu-update-2021-03/a-brief-history-of-time-in-data-modelling-oltp-systems.md
    RequestId: 01G5V90P4WF6CQHJ
    HostId: rs8UsRwKOGeyavaJ0zaRii+UCYvF381jf7YWjzw2p0Z9sUf2S/aOulr2QotbMxl90ucNtgAz9sA=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

**Comment by sergiimk** [comment]
The link is fixed now, thanks a lot for reporting!
